<?php

/**
 * Implementation of hook_menu()
 * @return array of menu items
 */
function test_menu() {
  $menu = array();

  $menu['test/testform'] = array(
    'title' => t('Test form'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dr_search_test_form'),
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  return $menu;
}

function dr_search_test_form($form, &$fstate) {
  $form["wrapper"] = array("#markup" => "<div id='test-ajax'></div>");
  $form["name"] = array("#type" => "textfield", "#required" => true, "#title" => "Name");
  $form["submit"] = array(
    "#type" => "submit", 
    "#value" => "Send", 
    "#ajax" => array(
    "callback" => "dr_search_test_form_callback", 
    "wrapper" => "test-ajax",
    "effect" => "fade"));
  return $form;
}

function dr_search_test_form_callback($form, &$fstate) {
  return "<div id='test-ajax'>Wrapper Div</div>";
}

/* END OF FILE */
