<?php

/**
 * @file
 * Enable consumer to register and make appointments.
 */
/**
 * Implements hook_permission().
 */

function bpost_zipcode_permission() {
  return array(
    'bpost zipcde log' => array(
      'title' => t('bpost zipcde logging'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function bpost_zipcode_menu() {
  $items = array();
  $items['admin/reports/zip'] = array(
    'title' => 'ZIP Statistics',
    'description' => 'Overview of the usage of ZIP codes on Shop&Deliver',
    'page callback' => 'bpost_zipcode_statistics',
    'access arguments' => array('bpost zipcde log'),
  );
  return $items;
}
/**
 * Implements callback bpost zicode statistics
 */
function bpost_zipcode_statistics() {
  $rows = array();
  $header = array('Zip codes', 'Amount');
  $columns = array('zipcode', 'zipcount');
  $query = db_select('zipcode_log', 'z');
  $query->fields('z', $columns);
  $results = $query->execute();
  while($record = $results->fetchAssoc()) {
    $rows[] = array($record['zipcode'], $record['zipcount']);
  }
  $per_page = 1;
  // Initialize the pager
  $current_page = pager_default_initialize(count($rows), $per_page);
  // Split your list into page sized chunks
  $chunks = array_chunk($rows, $per_page, TRUE);
  // Show the appropriate items from the list
  $output = theme('table', array('header' => $header, 'rows' => $chunks[$current_page]));
  // Show the pager
  $output .= theme('pager', array('quantity',count($rows)));
  return $output;
}
